import type { Metadata } from 'next';

import '../scss/main-style.scss';

export const metadata: Metadata = {
  title: 'EventGrid - Book Your Next Event',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
